### ISSUE TITLE
Info on data samples

### ISSUE THREAD

**Issue by mtetrault** [jgOhYeah/NonOfficial-StuffForCosmicWatchMuonDetectors#2]
Hi,

I'm preparing training exercices/homework on basic data analysis where we will eventually have CosmicWatch units assembled and generating the data to process. In the meantime I'm hoping to use public or loaned data sets from coincidence experiments, for example to reproduce figure 13 in the reference paper (https://github.com/spenceraxani/CosmicWatch-Desktop-Muon-Detector-v2/blob/master/ThePhysicsPaper.pdf) but I'm not sure if there are any available anywhere. 

I found the Master/Slave CSVs in this git repo, but it is unclear to me if the naming is just happenstance or if this set can be used to generate a similar figure. Would you be willing to comment?

Thanks!

**Comment by jgOhYeah** [comment]
Hello,
Good question on the csv files. It has been quite a while since I have touched this project and I don't have readily available access to the hardware anymore, so it has been a bit of interesting archeology :). The files were definitely recorded by a detector in each of their respective modes as per the filenames. There is a header with the name of the detector and what mode it is in at the top of each file, which seems to line up with the filenames.

I not sure if the csv files in the repository were recorded simultaneously. I don't think having different times for the master and slave data would have too great of an impact on generating something like figure 13 if the rate of muons and other events stayed fairly constant. Nonetheless, this zip file below has data that I am pretty sure was captured at the same time (the detectors would have been sitting on a bench, one sitting on top of the other and started within a few seconds of each other).

[MuonData.zip](https://github.com/jgOhYeah/NonOfficial-StuffForCosmicWatchMuonDetectors/files/7769756/MuonData.zip)

I haven't personally tried to generate such a graph, but assume that this data would work. Spencer would probably be the one to ask about the exact process.

Good luck with your analysis / task setting :)

**Comment by mtetrault** [comment]
Thanks for digging out these data sets! I got histograms for each file done pretty quickly and they independently make sense to me.

For coincidence resolution, I'm unsure if the two sets can be aligned easily. The "start" time for each board seems to be initialized independently in the setup loop : https://github.com/jgOhYeah/NonOfficial-StuffForCosmicWatchMuonDetectors/blob/fe0e902fd30c585e25229f44a283bf565645591a/Arduino%20Code/MuonDetector/MuonDetector.ino#L357

But I'm not sure how one can determine the offset/relationship between the two boards. I could assume both are started at more or less the same time, but the master/slave selection seem to be based on power-on order:
https://github.com/jgOhYeah/NonOfficial-StuffForCosmicWatchMuonDetectors/blob/fe0e902fd30c585e25229f44a283bf565645591a/Arduino%20Code/MuonDetector/MuonDetector.ino#L91-L100

The file naming also seems to suggest this, where in one set board A is master, B slave, then in reverse in the other set.

Do you remember anything about the bootup sequence for the pair and the possible approximate delay or offset?

Edit: I've gone through issues on the main repo just in case. A few cases on coincidence mode but not much on timestamp-based post-acq analysis so far. There was one mention of substracting the dead time to calculate the rate (which I've not done yet). Does this ring any bell? Might this also be required for backtracking coincidences in the Master?

For now, what I'm trying to do is to select events from the master based on timestamps from the slave, then look at the resulting histogram. I'm expecting to see the same histogram than the slave, assuming both sensors get a similar energy deposition. Perhaps my assumption is wrong...?

**Comment by jgOhYeah** [comment]
If I needed an event from the master corresponding to one on the slave, for each event on the slave, I would probably do what you are doing and look for a pattern of events on the master with a consistent offset to that of the slave and use this offset. To start off with, the master's timestamps will be a bit ahead (~ 0.7-1s from my rough guess / look last night) of the slave's as the master had to start up first. The master records every event while the slave only records those that match the master, so there will be a lot of events on the master to filter out.

From memory, one specific detector always started up before the other due to differences between individual units and thus became the master if the supply was connected at the same time for both. Otherwise to get it the other way around, you would have to manually control the power on / reset order, which would make the timestamps have a bigger offset relative to each other.

My understanding of the master and slave concept was that the master's data gets thrown away as unreliable and the slave's data is what gets used, however since you are planning to use both syncronisation would become important for comparing individual events. Bear in mind that the detectors I built used "clone" arduino nanos that didn't have the most accurate clocks, so over the course of a couple of days, could drift out by a few minutes relative to each other, then due to environmental effects, drift back the other way and generally wander around. When you build your own, I would recommend connecting them to a computer that has a real time clock and using this to log events so that the detectors stay in sync (Spencer had written scripts to do that from memory).

I was in high school when I built these and hadn't done much detailed data analysis then (the school mainly wanted these boxes to help show muons existed as part of the year 11 and 12 science curriculum and I was tasked with building rather than analysing). Apart from looking that the flashes looked similar to what Spencer was getting and the firmware was working (main reason that I actually had sd cards in them at the time), I haven't done much else on the data.

The dead time is pretty much the time the detector is doing stuff like updating the screen, writing to the sd card and waiting for the circuit to settle after a detection when it is not actively listening for an event while the timestamps include this time. Not having an sd card or screen enabled in one detector might make it grow slower than a detector with those enabled or connected. Unplugging an sd card unexpectedly can also really slow down a detector for some reason. Subtracting the dead time and the starting time from the current timestamp gives the time that the detector was actively looking for events, so dividing the number of events by this gives the rate of events for the time spent actually detecting rather than just being on. This calculation is done in oled.ino as an example:

https://github.com/jgOhYeah/NonOfficial-StuffForCosmicWatchMuonDetectors/blob/fe0e902fd30c585e25229f44a283bf565645591a/Arduino%20Code/MuonDetector/oled.ino#L111

For comparing events between detectors in this data, I would probably use the raw timestamps for finding event and only include the dead time if you are interested in rates.

**Comment by mtetrault** [comment]
Hi,

Thanks for the feedback, this is really helpful.

I've managed to write a first back-tracker code that does not take into account clock drift between the two units and it currently finds a sequence up to slave event #794 (master event #3302) with a couple of dual/quad match possibilities. Tracking the drift might be possible but will take more work. I'll be looking into it.

If I have trouble writing clock drift tracking, I might ask Spencer if he has a similar data set taken with the scripts you mentioned.

**Comment by jgOhYeah** [comment]
That sounds like good progress - I was having trouble matching past the first 10 with my lack of attention / effort, so good thinking on automating it and glad you have some hopefully more reliable data to use :).
All the best with it.
Jotham

**Comment by mtetrault** [comment]
The two strategies I wrote seem to match events up to a certain point (~3k events in the slave), but unfortunately the amplitude histogram is not what I expect it to be (coincident events overall above the noise/background) and I'm not sure what to try next. On the other hand, as you suggested, I wrote to Spencer and he posted the raw data for figure 13 on the main project github in issue 72, so I will be going with that one.

Thank you so much for your help and I wish you the best going forward. :)
